<?php

namespace App\Classes;

use Nevs\Config;
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception;

class Email
{
    /** What Storage::ContentType() returns when the extension tells it nothing. */
    private const FALLBACK_CONTENT_TYPE = 'application/octet-stream';

    /**
     * The content type to attach a file with. Without one PHPMailer falls back to application/octet-stream,
     * which is what makes a mailed PDF arrive as an unnamed binary blob some clients refuse to preview.
     *
     * The extension is trusted first: these files are generated by us or were uploaded under a name the user
     * chose, and it is also what the recipient's mail client will go by. Only when the extension says nothing
     * is the file itself sniffed, which covers uploads stored without a usable extension.
     */
    private static function AttachmentContentType(string $file): string
    {
        $content_type = Storage::ContentType($file);
        if ($content_type === self::FALLBACK_CONTENT_TYPE && function_exists('finfo_open')) {
            $finfo = finfo_open(FILEINFO_MIME_TYPE);
            if ($finfo !== false) {
                $detected = finfo_file($finfo, $file);
                finfo_close($finfo);
                if ($detected !== false && $detected !== '') {
                    $content_type = $detected;
                }
            }
        }
        return $content_type;
    }

    public static function Send($subject, $body, $recipients, $cc = [], $bcc = [], $attachments = []): void
    {
        if (Config::Get('mail.demo_recipient') != '') {
            $body .= '<hr />' . json_encode($recipients);
            $recipients = [Config::Get('mail.demo_recipient')];
        }

        if (count($cc) != 0) {
            if (Config::Get('mail.demo_recipient') != '') {
                $body .= '<hr />' . json_encode($cc);
                $cc = [];
            }
        }

        if (count($bcc) != 0) {
            if (Config::Get('mail.demo_recipient') != '') {
                $body .= '<hr />' . json_encode($bcc);
                $bcc = [];
            }
        }

        $mail = new PHPMailer(true);
        try {
            $mail->CharSet = "UTF-8";
            $mail->Debugoutput = 'error_log';
//                $mail->SMTPDebug = SMTP::DEBUG_SERVER;                      //Enable verbose debug output
            $mail->isSMTP();                                            //Send using SMTP
            $mail->Host       = Config::Get('mail.host');           //Set the SMTP server to send through
            $mail->SMTPAuth   = true;                                   //Enable SMTP authentication
            $mail->Username   = Config::Get('mail.username');       //SMTP username
            $mail->Password   = Config::Get('mail.password');      //SMTP password
            $mail->SMTPSecure = Config::Get('mail.encryption');            //Enable implicit TLS encryption
            $mail->Port       = Config::Get('mail.port');           //TCP port to connect to; use 587 if you have set `SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS`

            //Recipients
            $mail->setFrom(Config::Get('mail.from'), Config::Get('mail.from_name'));
            foreach($recipients as $recipient) {
                $mail->addAddress($recipient);
            }
            foreach($cc as $cc_address) {
                $mail->addCC($cc_address);
            }

            foreach($bcc as $bcc_address) {
                $mail->addBCC($bcc_address);
            }

            //Attachments
            foreach ($attachments as $file) {
                $mail->addAttachment($file, basename($file), PHPMailer::ENCODING_BASE64, self::AttachmentContentType($file));
            }

            //Content
            $mail->isHTML(true);                                  //Set email format to HTML
            $mail->Subject = $subject;
            $mail->Body    = $body;

            $mail->send();
        } catch (Exception $e) {
            error_log ("Mailer Error: {$mail->ErrorInfo}");
        }
    }
}
